// api
const api = {
  // 登录
  login: "/admin/login-by-username",
  // 新增管理员
  addAdmin: "/admin/add",
  // 获取用户信息
  getInfo: "/admin/get-my",
  // 修改管理员
  updateAdmin: "/admin/update",
  // 搜索管理员
  searchAdmin: "/admin/search",
  // 新增角色
  addRole: "/admin/add-role",
  // 修改角色
  updateRole: "/admin/update-role",
  // 搜索角色
  searchRole: "/admin/search-role",
  // 搜索权限
  searchPermission: "/admin/search-permission",
  // 新增公告
  addNotice: "/notice/add",
  // 搜索公告
  searchNotice: "/notice/search",
  // 修改公告
  updateNotice: "/notice/update",
  // 删除公告 /notice/delete/{id}
  deleteNotice: "/notice/delete",
  deleteSelectedNotice: "/notice/batch-delete",
  // 搜索收藏
  searchCollection: "/collection/search",
  // 搜索用户
  searchUser: "/user/search",
  // 删除用户 /user/delete/{id}
  deleteUser: "/user/delete",
  // 修改用户信息
  updateUser: "/user/update",
  // 解绑证照 /card/unbind/{id}
  unbindCard: "/card/unbind",
  // 搜索亮照
  searchCard: "/card/search",
  searchCardShown: "/card/search-shown",
  // 搜索事项
  searchItems: "/items/search",
  // 获取卡证类型
  getCardType: "/card/list-type",
  // 用户导出
  userDownload: "/user/download",
  // 导出证照
  cardDownload: "/card/download",
  // 导出亮证
  cardDownloadShown: "/card/download-shown",
  // 导出事项
  itemsDownload: "/items/download",
  // 导出管理员
  adminDownload: "/admin/download",
  // 导出角色
  downloadRole: "/admin/download-role",
  // 导出收藏
  collectionDownload: "/collection/download",
  // 1.查询访问用户数量
  getVisitCount: "/user/analysis/get-visit-count",
  // 查询本月本周活跃用户
  getVisitRate: "/user/analysis/get-visit-rate",
  // 获取指定时间内的活跃用户
  getVisitStatistics: "/user/analysis/get-visit-statistics",
  // 用户画像
  getVisitPortrait: "/user/analysis/get-visit-portrait",
  // 事项增长比例
  getStatisticsRate: "/items/statistics-rate",
  // 事项趋势统计
  getStatisticsTrend: "/items/statistics-trend",
  getMessages: "/messages",
  // 获取字典数据
  getDict: "/dict",
  // 搜索可网办列表
  searchCanNetwork: "/items/search-can-network",
  // 设置可网办
  setCanNetwork: "/items/set-can-network",
  loginVerify: "/admin/login-verify",
};
export default api;
